language: ruby
rvm:
- 2.2
cache: bundler
script:
- bundle exec middleman build -e production
deploy:
  provider: s3
  access_key_id: AKIAJS74CLEP7FQBOVBQ
  secret_access_key:
    secure: XKE35fKljANTCSLaqA89a02Fo4LQEpiyzC/ZHTELL7qF35bV/5ehP1Sy6pYxeF63x7cJtgpRSh5PKXe2hr3goGWs4rXSTRdAB/fDQs16sB5iJzLzWbOwaMfrb5ULiBcbgIcX6EzrlibgMhrRGOonlEHUDzd5RpVHilZ5eKVgTqZmRPyQnbwmmWdW+4+MMBFcOyqmr17ievTOSQiZ93oVLSJUT9nCa3peA02nD3omF07/oB2QwvzDTFo7UVqTSUfmE6IlOHgdTewoTvdrS6ItnahUkQil7KEK/T4QXFz/WXU1W2wE0DIPSA9aVBqv+4j5vY6+lBP3gkMtRvnNwjhg6io9anp/jK2ynt9hV/b6sxpgE7WwDW751/ZODOHyIYxW2cdxWUEpqk/QDU8aHmKrWE+xYgZT3orr1PcDa3im4ZppZCapsiQVfzsWu1DjUVzUZ0Y+TRxhT8pl3gnCLoyvpmrdz5pPccs2+h55gjFkSAF9om9jaqbJPf6gloJzOIdEJdtUiZFzcaYpDCihj6cvudVcSiWzryfIURGRlZMfDYCSLDJAe7rlBInrg4ceZYpPEeoRbhGxrjZ+iX7JpxJiKC5mw8R7cnOe4M4rzzsK9Io2gPNiLSEQXodJha78aU3igVASk6kcIau/FragXt88eMiT9I7/OGHpo8Zbr0pvRzQ=
  bucket: www.pidapalooza.org
  local-dir: build
  skip_cleanup: true
  acl: public_read
  on:
    repo: pidapalooza/website
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
